name: svp_admin_pm
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies: 
  flutter: 
    sdk: flutter
  provider: ^6.0.5
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  grouped_list: ^5.1.2
  intl: ^0.17.0
  calendar_timeline: ^0.7.1
  animated_horizontal_calendar: ^0.0.3
  dio:
  get_it: ^3.1.0
  http:
  flushbar:
  sembast:
  font_awesome_flutter:
  firebase_auth:
  google_sign_in:
  firebase_messaging: ^14.1.0
  flutter_screenutil: ^5.6.0
  cloud_firestore:
  firebase_core: ^2.8.0
  firebase_database:
  firebase_storage:
  shared_preferences:
  pretty_dio_logger: ^1.1.1
  dio_http_cache:
  flutter_spinkit: ^4.1.2+1
  pk_skeleton: ^0.0.2
  image_picker: ^0.8.4+1
  multi_image_picker:
  readmore: ^2.1.0
  fluttertoast:
  timeago:
  file_picker:
  modal_progress_hud: ^0.1.3
  path_provider: ^2.0.1
  http_parser:


dev_dependencies:
  flutter_test: 
    sdk: flutter
  flutter_launcher_icons: ^0.9.1

flutter_icons:
  image_path: "assets/images/img_svppnglogo1.png"
  android: true
  ios: true
# optionally, as transparency is not allowed on app store
  # remove_alpha_ios: true

flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
        - asset: assets/fonts/InterBold.ttf
          weight: 700
